# Bill Splitter
version: '3.1'
services:
  backend:
    container_name: bill-splitter
    image: bill-splitter/bill-splitter-backend:latest
    ports:
      - "3000:3000"
    expose:
      - 3000
    depends_on:
      - database
  database:
    container_name: bill-splitter-database
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    expose:
      - 5432
    environment:
      - POSTGRES_PASSWORD=bill-splitter
      - POSTGRES_USER=bill-splitter
    volumes:
      - bill-splitter-database:/var/lib/postgresql/data
volumes:
  bill-splitter-database:
networks:
  default:
    external:
      name: webproxy