name: build on renovate PR
'on':
  pull_request:
    branches:
      - 'renovate/*'
jobs:
  build-backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: bill-splitter-backend
    steps:
      - uses: actions/checkout@v2
      - run: npm ci && npm run build:dev
  build-frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: bill-splitter-frontend
    steps:
      - uses: actions/checkout@v2
      - run: npm ci && npm run build
